version: '3.8'

services:
  # 1. Web Server (PHP + Apache)
  php_web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db_mysql

  # 2. Database MySQL
  db_mysql:
    image: mysql:8.0
    container_name: php_mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: php_demo_db
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - mysql_data:/var/lib/mysql

  # 3. phpMyAdmin (Quản lý DB)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db_mysql
      # Nếu muốn tự động điền mật khẩu thì dùng dòng dưới (không bắt buộc)
      PMA_PASSWORD: mysecretpassword 
    depends_on:
      - db_mysql

volumes:
  mysql_data: